package com.wblut.geom;

public enum WB_Classify {
	FRONT, BACK, ON, CROSSING, SPANNING, FRONTEXCL, BACKEXCL, CROSSINGEXCL, INSIDE, OUTSIDE, OBLIQUE, INLINE, PARALLEL, ANTIPARALLEL, PERPENDICULAR, COLLINEAR, COPLANAR, SAME, DIFF, SAMEEXCL, DIFFEXCL, CLOCKWISE, COUNTERCLOCKWISE
}
